apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: .dkr.ecr..amazonaws.com/demo-frontend
  newName: .dkr.ecr..amazonaws.com/demo-frontend
  newTag: abcdefg
- name: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/wsc2024-ecr
  newName: 950274644703.dkr.ecr.ap-northeast-2.amazonaws.com/wsc2024-ecr
  newTag: c3e43bcf
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
